#include <iostream>

extern void print(int a) asm("print");

// ffi to the chococ compiler
void print(int a) {
    std::cout<<a<<std::endl;
}

// this file will link against the llvm code that is generated by the chococ compiler
int main() {
    
}